// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenVision.Server.EntityFramework.DbContexts;



#nullable disable

namespace Vision.Web.Api.EntityFramework.PostgreSQL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240712192743_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vision.Web.Api.EntityFramework.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DatabaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DatabaseId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("Vision.Web.Api.EntityFramework.Entities.Database", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Databases");
                });

            modelBuilder.Entity("Vision.Web.Api.EntityFramework.Entities.ImageTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveFlag")
                        .HasColumnType("integer");

                    b.Property<byte[]>("AfterProcessImage")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("AfterProcessImageWithKeypoints")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DatabaseId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Descriptors")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("DescriptorsCols")
                        .HasColumnType("integer");

                    b.Property<int>("DescriptorsRows")
                        .HasColumnType("integer");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<byte[]>("Keypoints")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PreprocessImage")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("Recos")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("DatabaseId");

                    b.ToTable("ImageTargets");
                });

            modelBuilder.Entity("Vision.Web.Api.EntityFramework.Entities.ApiKey", b =>
                {
                    b.HasOne("Vision.Web.Api.EntityFramework.Entities.Database", "Database")
                        .WithMany("ApiKeys")
                        .HasForeignKey("DatabaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Database");
                });

            modelBuilder.Entity("Vision.Web.Api.EntityFramework.Entities.ImageTarget", b =>
                {
                    b.HasOne("Vision.Web.Api.EntityFramework.Entities.Database", "Database")
                        .WithMany("ImageTargets")
                        .HasForeignKey("DatabaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Database");
                });

            modelBuilder.Entity("Vision.Web.Api.EntityFramework.Entities.Database", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("ImageTargets");
                });
#pragma warning restore 612, 618
        }
    }
}
